on:
  push:
    branches:
      - prod

jobs:
  build_docs:
    runs-on: ubuntu-latest
    name: Builds documentation and publishes to GitHub Pages
    steps:
      # Checkout repo
      - uses: actions/checkout@v1
        name: Checkout repo

      # Install NuGet
      - uses: nuget/setup-nuget@v1
        name: Install NuGet

      # Install NuGet dependencies
      - name: Install NuGet dependencies
        run: nuget restore JotunnLib.sln

      # Needed so csproj can load correctly, isn't actually used
      - name: Set references to DLLs
        run: |
          echo "<?xml version=\"1.0\" encoding=\"utf-8\"?><Project ToolsVersion=\"Current\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\"><PropertyGroup><VALHEIM_INSTALL>$HOME/VHINSTALL/</VALHEIM_INSTALL></PropertyGroup></Project>" > Environment.props

      # Build docs
      - uses: nikeee/docfx-action@v1.0.0
        name: Build documentation
        with:
          args: JotunnLib/docfx.json
          args: metadata --shouldSkipMarkup

      # Publish generated site using GitHub Pages
      - uses: maxheld83/ghpages@master
        name: Publish documentation to GitHub Pages
        env:
          BUILD_DIR: JotunnLib/_site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
